### ISSUE TITLE
Build fails using Python 3.5.2

### ISSUE THREAD

**Issue by degenerated1123** [pret/pokered#136]
I'm using Arch Linux here and got "python" pointing to Python 3.5.2.

Typing "make" would result in the following message:
```
$ make                                                                                                  
rgbasm -D _RED -h -o audio_red.o audio.asm                                                                                        
  File "extras/pokemontools/gfx.py", line 72                                                                                      
    tiles = sorted(enumerate(tiles), key= lambda (i, tile): i % width) 
```

A workaround for me was to modify the first line of the Makefile from `PYTHON := python` to `PYTHON := python2.7`.

**Comment by LyndonArmitage** [comment]
I ran into the same issue as well but not having fiddled with make or python in a long time came up with a different (heavier solution):

I actually ended up writing a very quick [Dockerfile](https://www.docker.com/) to run the build in instead; a bit overkill but I had done something similar earlier to workaround a versioning issue in a project at work.

Basically it creates a little container which has all the requirements to build within it (including rgbds) and provided it's run with the pokered directory mounted within it it can build the rom files:
```bash
docker run -i --rm -v $PWD:/build rgbds
```

```
FROM python:2
VOLUME /build
WORKDIR /build
RUN apt-get update
RUN apt-get -q -y install make gcc bison git
RUN git clone https://github.com/bentley/rgbds /rgbds
RUN make -C /rgbds install
CMD [ "make", "-C", "/build" ]
```

I share this because it might be useful in adding an automated build or something else further down the line.

**Comment by iimarckus** [comment]
> A workaround for me was to modify the first line of the Makefile from `PYTHON := python` to `PYTHON := python2.7`.

You can get the effect you want without editing the makefile by running `make PYTHON=python2.7`. That’s why it’s written like that.

That’s not the ideal solution. But there is no consistency across Unix operating systems when it comes to the name of the Python 2 binary, which means that there *is* no ideal solution, unfortunately.

**Comment by Sanqui** [comment]
>That’s not the ideal solution. But there is no consistency across Unix operating systems when it comes to the name of the Python 2 binary, which means that there is no ideal solution, unfortunately.

Well, we could always make pret compatible with Python 3.  There's [six](https://pypi.python.org/pypi/six) for that.  It would work for a solution.

**Comment by iimarckus** [comment]
Have at it… I have no objection.

**Comment by degenerated1123** [comment]
I'd say it would be great if you could give a hint about that in the `INSTALL.md`.
