### ISSUE TITLE
.blk Readability

### ISSUE THREAD

**Issue by knuxyl** [pret/pokered#158]
I'm assuming the map files .blk are hex files. Do you think it would be possible to have these in a readable format and then converted back to hex during make?

Like have it in ascii format

HEADER
tile (0,0)(tile#,special1,special2)
tile (0,1)(tile#,special1,special2)

Since it isn't assembly code and just standard bytes I think making it user friendly in source would be great. This would make map editing much easier

**Comment by dannye** [comment]
We have had a few discussions like this before.
I think that the main reason we haven't taken the time to do this is because it wouldn't actually make map editing much easier necessarily.
The most productive way to edit maps is by editing them graphically in another program.
If another program is reading and modifying the actual .blk files, it's fine if the .blk files remain as binary files.
I don't speak for everyone here though.

**Comment by knuxyl** [comment]
So you're saying that the .blk files have actual images in them? I thought they were just hex codes that the engine would real from a palette and load the corresponding hex code from the palette.

**Comment by dannye** [comment]
No, I'm saying most of us use things like [crowdmap](https://github.com/yenatch/crowdmap) and [GlitchMap](https://github.com/TheFakeMateo/RedPlusPlus/tree/master/GlitchMap) to edit the .blk files.

The .blk files are just sequences of block IDs. No palettes involved.

**Comment by huderlem** [comment]
I agree with Danny.  For Pokemon, graphical map editing will always be more practical than text editing in any form.  However, I think it would be cool  if we blessed one of the existing map editors and included it in  the pokemon-reverse-engineering-tools repo (the "extras" submodule).  We could include instructions in the README.md.  Even better, we could create a new README.md in the https://github.com/pret/pokered/tree/master/maps directory, which would explain what the .blk files are and how to use the map editor.

**Comment by huderlem** [comment]
We should come up with a list of what would make a map editor good enough to endorse for pokered, so we can take action on it.  My quick list:

1. Cross-platform (Windows/Mac/Linux).  Many options to achieve this.
2. Provide interactive editing for .blk data. (This is assumed).
3. Edit signs, warps, npcs
  * npcs should be displayed using the correct sprite sheets
  * Hitting "save" should update the mapObjects .asm files accordingly.  .blk files can stay in their current format.
4. Map connection editing

I think one important decision to make is if the map editor would read data from a built ROM (RBMap) or from the the raw source files (GlitchMap).  Some pros cons of both approaches:

## Read data from built ROM
### Pros
- Don't have to parse text, whose format could potentially change over time. (e.g. new warp macro)
- Can read location of data structures from the symbol (.sym) files, which are output from the build.

### Cons
- How do you know which data belongs to which .asm files?
- Requires a working build environment to acquire the ROM.
- Will be outputting .asm files when saving changes to warps/npcs/signs/etc., so why not just parse the .asm files to begin with?

## Read data from raw source files
### Pros
- Don't need a built ROM.  Can simply git clone and start editing.  However, this isn't a huge plus because you'll want to build the ROM immediately after saving anyway.

### Cons
- The format of the .asm files could change over time.  For example, new macros.  This would require a change to the map editor's parsing logic.

I hope that's a decent start to the conversation.

**Comment by Fotomac** [comment]
I might use HexEdit for mapping. It's basically as simple as memorizing the hexadecimal correspondences to each individual 32x32 tile and writing each map accordingly. That's the gist of the hex editing method, anyway.

**Comment by yenatch** [comment]
The major issue with crowdmap (and i presume glitchmap) is they use a browser instead of something like electron (which was not mature yet). So the user has to run a python server and deal with the browser obstinately caching files. I think at least crowdmap could be easily ported to electron. It's not the best editor ever but I think that alone would make it usable.

**Comment by yenatch** [comment]
https://github.com/Rangi42/polished-map
