### ISSUE TITLE
If you're avoiding the Discord, please don't.

### ISSUE THREAD

**Issue by ProjectRevoTPP** [pret/pokered#182]
I'm talking to you, @padz.

**Comment by mid-kid** [comment]
Context: We've had an NSFW raid two days ago that lasted a bit too long for most people's tastes. The spammer kept up and the users of the pret discord felt powerless to do anything against it, due to the absence of moderation. The attacker thankfully stopped, and discord has been notified of the infraction.

This has sparked conversation about what should be done to prevent this in the future. It doesn't help that the only kind of moderation we have on the discord has suddently gone missing for what is uncomfortably long. Most people seem to agree that more moderation is warranted, to reduce the bus factor by being able to cover when one mod is gone. Some have even taken it thus far that they're fed up with the status quo and are trying to get people to move over to other servers, at least as a temporary "solution".

This is a formal request, by what I think is most of the pret crew active during these days on the discord, for you, @padz, to get on the discord to try to find a solution to this. Some people are angry, others simply want this to be over with, but letting this slip by, especially given how unnecessarily high this has escalated, is simply not a solution.

Thanks.

**Comment by ProjectRevoTPP** [comment]
Censorship now? That's unlike you, Shanty.

**Comment by dannye** [comment]
"Issues" is just a weird place to do this. I've messaged padz on irc and I have emailed him. We will hear from him when we hear from him.

**Comment by ProjectRevoTPP** [comment]
It was not necessary to delete the comment.
