### ISSUE TITLE
Issue locating data

### ISSUE THREAD

**Issue by VentaVoltage** [pret/pokered#199]
So I've searched for where in pokered is the data for the pokemon's nest is. Like, the pokedex area section displays that you can find a pidgey on route 1 and 2, and I was wondering what .asm file this is located in. I changed some pokemons locations, and want to change the nest information to reflect this. Thanks!

**Comment by Pokechu22** [comment]
At the highest level:

https://github.com/pret/pokered/blob/725b86ebbec23bd1f53fd60bf0201c904fee951d/engine/menu/pokedex.asm#L150-L153

which then calls `LoadTownMap_Nest`:

https://github.com/pret/pokered/blob/725b86ebbec23bd1f53fd60bf0201c904fee951d/engine/town_map.asm#L112-L132

which calls `DisplayWildLocations`:

https://github.com/pret/pokered/blob/725b86ebbec23bd1f53fd60bf0201c904fee951d/engine/town_map.asm#L369-L415

which calls `FindWildLocationsOfMon`:

https://github.com/pret/pokered/blob/725b86ebbec23bd1f53fd60bf0201c904fee951d/engine/items/items.asm#L2942-L2989

which directly works off of the data in `WildDataPointers` in `data/wild_mons.asm`.

So at least to me, it looks like it works directly off of the existing data and you shouldn't need to do anything special to update it.  But I'm not particularly familiar with the codebase, and this is just from me briefly looking, so if you're running into issues still then I might have missed something.

**Comment by VentaVoltage** [comment]
Thanks for the answer! This has helped me better understand it. I think my problem is that I added more wild pokemon slots then usual (typically 10, but I added 10 more), leading to my pokedex nest information being messed up. I will have to look into this further.

**Comment by dannye** [comment]
@VentaVoltage The number of wild mon is hard-coded as 10.
Take a look at the last routine that @Pokechu22 provided:
https://github.com/pret/pokered/blob/725b86ebbec23bd1f53fd60bf0201c904fee951d/engine/items/items.asm#L2973-L2989

`ld b, $a` is used as the loop counter, so this loop only checks the first 10 ($a) bytes before exiting.

If you want to increase the number of wild mon, you would need to update all the places where this assumption of 10 is hard-coded.

And you would have to either: make this new, larger number used by all maps (as in, if you increase the number of wild mons in one map to 20, you need to increase the number of wild mons in all maps to 20).
Or you would have to do a bit bigger of a rewrite of the relevant code so that the number of wild mons in a map is dynamic and terminated by a special value ($FF), and then the code would have to loop indefinitely and check for this terminator value.

**Comment by VentaVoltage** [comment]
Oh okay, thank you, too! I don't know much about this stuff (been learning on my own for two months or so), so thanks! I did not know that the loop checked only 10 slots. I'll be sure to edit that.

**Comment by VentaVoltage** [comment]
Are there any more examples in the code of the hard coded 10 slots, loops or otherwise (obviously ignoring engine/battle/wild_encounters and all of the data/wildpokemon)? My nest information is still inaccurate
