### ISSUE TITLE
Best way to modify and/or mute the music?

### ISSUE THREAD

**Issue by IoIxDButStronger** [pret/pokered#200]
**I went on Google and found a program that could convert Famitracker into .asm files, (see bottom of the post)** but it's either outdated or works with another disassembly (I've linked it below, however keep in mind it's meant to be blank; I'm trying to mute all the Pokemon cries for a meme hack). Whats the best way to make Famitracker files (or any files for that matter) work with this disassembly? 

[.asm file for the music I want to make, if it helps.](https://pastebin.com/raw/TjwfuSgD)

[Program that converts Famitracker project files into .asm files](http://www.pokemonhackersonline.com/attachment.php?attachmentid=77&d=1373992712)

**Comment by Pokechu22** [comment]
If your goal is to just mute it, you probably don't need to bother with converting.  Also, the cry format is actually different from the song music to my understanding (as a quick guess from the repo structure without any major grounds, my guess is that there's a way to play sfx from within music since it's also used for drums and such, and I think I've heard crys in the middle of glitch music).

There's some absurdly in-depth documentation of it [here](https://www.youtube.com/watch?v=gDLpbFXnpeY), and the actual cry sfx is [here](https://github.com/pret/pokered/tree/725b86ebbec23bd1f53fd60bf0201c904fee951d/audio/sfx).  Actual cry data is stored [here](https://github.com/pret/pokered/blob/725b86ebbec23bd1f53fd60bf0201c904fee951d/data/cries.asm) -- and you'll want to look at that video for more explanation as to what the parameters exactly mean.

The simple and lazy way you probably could do this is just blank one of the cry sfx files, and change all of the cries in that list to point to that one.  Or you could modify/blank the code that actually is responsible for playing it:

https://github.com/pret/pokered/blob/725b86ebbec23bd1f53fd60bf0201c904fee951d/home.asm#L309-L343

You mention that this is a meme hack... so you could also do some even stupider stuff.  Looking at the [sound effect headers](https://github.com/pret/pokered/blob/725b86ebbec23bd1f53fd60bf0201c904fee951d/audio/headers/sfxheaders1.asm) I see some possibly fun sound effects after the cries, e.g. `Denied` (which is 24 or $18 after the highest cry, $25, so you'd use $3D to reference it).  To access the ones before that list you'd probably need to change the cry function because it always adds $14 or use negative numbers; I'm not sure how that'd work exactly.

Disclaimer: I have no idea what I'm doing, and I haven't actually made a hack.  I just like tinkering.  My advice very well may not work.
