### ISSUE TITLE
Upload .sym files to a 'symbols' branch

### ISSUE THREAD

**Issue by Rangi42** [pret/pokered#248]
pokegold and pokecrystal have a `symbols` branch which just contains the .sym files created when Travis runs. This makes it unnecessary to have address comments in the source itself.

**Comment by dannye** [comment]
I really don't like the idea of a symbols branch. If we feel strongly enough about putting the sym file in git (which I don't) then we should just put it in the master branch.
And what address comments are left? I thought I already removed all of them.

**Comment by Rangi42** [comment]
RAM still has address comments.

The reason for a separate branch is so that `master` doesn't get spammed with extra commits, which anyone who's checked out the repo would have to pull. Alternatives could be a GitHub release with .sym files as uploaded assets, or a separate pokered-syms repo.

**Comment by dannye** [comment]
If we choose the keep the sym file somewhere, it should be the master branch. There wouldn't be any spam of any extra commits because contributors would just update the file when they make other changes. I wouldn't get Travis involved in this. Anything else is needlessly complex and isolated.
I still disagree with adding it in any form. If someone wants a build artifact, they should build the project.

**Comment by Rangi42** [comment]
Alright, fair enough.

**Comment by dannye** [comment]
As far as the wram.asm and sram.asm address comments, I think it is fine to delete them.
I originally left them when deleting all other address comments (https://github.com/pret/pokered/commit/a51037eeeedb03e29d8675626018cf02750882fa) because they're far more handy than any random asm address comment. But that doesn't mean keeping them is a good idea.

**Comment by Rangi42** [comment]
Coming back to this since there's more discussion on Discord: .sym files in `master` might work as long as people don't have to manually update them. If `make compare` copied the .syms to a symbols/ directory when the build is OK, that would work (not 100% foolproof, but hopefully people run `make compare` even for trivial updates).

**Comment by Rangi42** [comment]
Another type of address comment that exists is struct-pattern ones, mostly in engine/overworld/, like:

- `; c2x0=16: walk animation counter`
- ` ; c1x1 = 2 (set movement status to delayed)`
- `; c1x9: facing direction`

If these structs have relevant macro labels or constants, those can be mentioned instead.

**Comment by dannye** [comment]
Good point. That is also related to task 3 from #240

**Comment by iimarckus** [comment]
I feel strongly that generated files don’t belong in the master branch.

**Comment by entrpntr** [comment]
For a possible alternative, could there be occasional use of git tags to demarcate between substantial progress points? Each tag could have .sym files associated with it in github releases, which would allow the artifacts to exist without being committed to git. 

If tags were used, maybe it could also be recommended for users creating new hacks to base work off of the most recent tag/milestone (to limit the number of branching points). Really I'm just thinking out loud and unsure if any of this would be a sensible solution/compromise.

**Comment by coltongit** [comment]
Might do it like how pokecrystal does it and use the symbols for whatever is also used with pokecrystal
